<?php
/**
 * @file
 * Code for the News section feature.
 */

include_once('oc_news.features.inc');

/**
 * Implementation of hook_menu().
 */
function oc_news_menu() {
  $items = array();

  $items['admin/workbench/content/articles/add'] = array(
    'title' => 'Add article',
    'type' => MENU_LOCAL_ACTION,
    'page callback' => 'drupal_goto',
    'page arguments' => array('node/add/article', array('query' => array('destination' => 'admin/workbench/content/articles'))),
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Implements hook_preprocess_node().
 * Add a custom date variable.
 */
function oc_news_preprocess_node(&$vars) {
  $node = $vars['node'];

  switch($node->type) {
    case 'article':
      $wrapper = entity_metadata_wrapper('node', $node);
      $from = $wrapper->field_article_date->value();

      $html = '';
      if ($from) {
        $html = '<span class="date-wrapper">';
        $html .=
          '<span class="date-item date-from">' .
          '<span class="day">' . date('j', $from) . '</span> ' .
          '<span class="month">' . date('M', $from) . '</span> ' .
          '</span>';
        $html .= '<span class="date-item year">' . date('Y', $from) . '</span>';
        $html .= '</span>';
      }
      $vars['news_date_icons'] = $html;
      break;
  }
}

/**
 * Implements hook_preprocess_views_more().
 */
function oc_news_preprocess_views_more(&$vars) {
  if (isset($vars['view']) && $vars['view']->name == 'news') {
    $vars['link_text'] = $vars['link_text'] . ' ' . theme('fonticon_icon', array('icon' => 'arrow-right'));
  }
}

/**
 * Implements hook_migrate_api().
 */
function oc_news_migrate_api() {
  $api = array(
    'api' => 2,
    'migrations' => array(
      'OCNews' => array('class_name' => 'OCNews'),
    ),
  );
  return $api;
}

/**
 * Implements hook_field_default_fields_alter().
 *
 * Set the default image.
 */
function oc_news_field_default_fields_alter(&$fields) {
  $image_field = 'node-article-field_article_image_teaser';
  if (isset($fields[$image_field]['field_config']['settings']['default_image'])) {
    $fid = $fields[$image_field]['field_config']['settings']['default_image'];
    $fields[$image_field]['field_config']['settings']['default_image'] = variable_get('oc_news_default_image_fid', $fid);
  }
}

