<?php
/**
 * @file
 * Code for the OC Work Package feature.
 */

include_once 'oc_wp.features.inc';

/**
 * Implementation of hook_menu().
 */
function oc_wp_menu() {
  $items = array();

  $items['admin/workbench/content/wp/add'] = array(
    'title' => 'Add work package',
    'type' => MENU_LOCAL_ACTION,
    'page callback' => 'drupal_goto',
    'page arguments' => array('node/add/wp', array('query' => array('destination' => 'admin/workbench/content/wp'))),
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Implements hook_preprocess_node().
 */
function oc_wp_preprocess_node(&$vars) {
  $node = $vars['node'];

  switch($node->type) {
    case 'wp':
      $vars['wp_read_more'] = '<div class="read-more">' . l(t('Read more') . ' ' . theme('fonticon_icon', array('icon' => 'arrow-right')), 'node/' . $node->nid, array('html' => TRUE)) . '</div>';
      break;
  }
}

/**
 * Implements hook_migrate_api().
 */
function oc_wp_migrate_api() {
  $api = array(
    'api' => 2,
    'migrations' => array(
      'OCWorkPackages' => array(
        'class_name' => 'OCWorkPackagesMigration',
        'group_name' => 'OCMigrations'
      ),
    ),
  );
  return $api;
}
