<?php
/**
 * @file
 * oc_news.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function oc_news_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "context" && $api == "context") {
    return array("version" => "3");
  }
  if ($module == "ds" && $api == "ds") {
    return array("version" => "1");
  }
  if ($module == "flexslider" && $api == "flexslider_default_preset") {
    return array("version" => "1");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function oc_news_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_image_default_styles().
 */
function oc_news_image_default_styles() {
  $styles = array();

  // Exported image style: jcarousel_thumbnail.
  $styles['jcarousel_thumbnail'] = array(
    'effects' => array(
      7 => array(
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => 63,
          'height' => 40,
        ),
        'weight' => 1,
      ),
    ),
    'label' => 'jcarousel_thumbnail',
  );

  // Exported image style: square_small.
  $styles['square_small'] = array(
    'effects' => array(
      1 => array(
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => 100,
          'height' => 100,
        ),
        'weight' => 1,
      ),
    ),
    'label' => 'square_small',
  );

  return $styles;
}

/**
 * Implements hook_node_info().
 */
function oc_news_node_info() {
  $items = array(
    'article' => array(
      'name' => t('Article'),
      'base' => 'node_content',
      'description' => t('Use <em>articles</em> for types of content that depend on a date and time like news, press articles or blog entries.'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
