<?php
/**
 * @file
 * Code for the oc_promote feature.
 */

include_once('oc_promote.features.inc');

/**
 * Implements hook_init().
 */
function oc_promote_init() {
  // Use flexslider always
  libraries_load('flexslider');
  drupal_add_js(drupal_get_path('module', 'oc_promote') . '/oc_promote.js');
}

/**
 * Implementation of hook_menu().
 */
function oc_promote_menu() {
  $items = array();

  $items['admin/workbench/content/featured-content/add'] = array(
    'title' => 'Add featured content',
    'type' => MENU_LOCAL_ACTION,
    'page callback' => 'drupal_goto',
    'page arguments' => array('node/add/featured-content', array('query' => array('destination' => 'admin/workbench/content/featured-content'))),
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Implement hook_block_info()
 */
function oc_promote_block_info() {

  $blocks['oc-promote-info'] = array(
    'info' => t('OC short description'),
    'cache' => DRUPAL_CACHE_GLOBAL,
    'region' => 'sidebar_first',
  );

  return $blocks;
}

/**
 * Implement hook_block_configure()
 */
function oc_promote_block_configure($delta = '') {
  $form = array();

  switch ($delta) {
    case 'oc-promote-info':

      // body of the block
      $form['oc_promote_info_block_content'] = array(
        '#type' => 'textarea',
        '#title' => t('Content'),
        '#default_value' => variable_get('oc_promote_info_block_content', ''),
      );

      break;
  }

  return $form;
}

/**
 * Implement hook_block_save()
 */
function oc_promote_block_save($delta = '', $edit = array()) {

  switch ($delta) {
    case 'oc-promote-info':
      variable_set('oc_promote_info_block_content', $edit['oc_promote_info_block_content']);
      break;
  }
}

/**
 * Implement hook_block_view()
 */
function oc_promote_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'oc-promote-info':
      $block['subject'] = t('About 4DCellFate');
      $block['content'] = array(
        '#markup' => t(variable_get('oc_promote_info_block_content', '')),
        '#contextual_links' => array(
          'wordpress_blog' => array('node/add', array()),
        ),
      );
      break;
  }

  return $block;
}

/**
 * Implementation of hook_node_view().
 */
function oc_promote_node_view($node, $view_mode, $langcode) {
  $types = array(
    'featured_content',
  );

  if (in_array($node->type, $types) && $view_mode == 'full') {
    drupal_set_message(t('You have been redirected to the edit page of this featured content. If you wish to organize the order of the featured content on the homepage, please click !here.', array('!here' => l(t('here'), 'admin/workbench/content/featured-content'))));
    drupal_goto('node/' . $node->nid . '/edit');
  }
}

/**
 * Implements hook_preprocess_node().
 */
function oc_promote_preprocess_node(&$vars) {
  $node = $vars['node'];
  switch($node->type) {
    case 'featured_content':
      $wrapper = entity_metadata_wrapper('node', $node);
      $html = '';
      if ($wrapper->field_promoted_content->value()) {
        $nid = $wrapper->field_promoted_content->value()->nid;
        $link = l(t('Read more') . theme('fonticon_icon', array('icon' => 'arrow-right')), 'node/' . $nid, array('html' => TRUE));
        $html = '<div class="more-link">' . $link . '</div>';
      }
      $vars['promoted_read_more'] = $html;
      break;
  }
}

/**
 * Implementation of template_preprocess_field().
 */
function oc_promote_preprocess_field(&$variables) {
  // field_promoted_media
  if ($variables['element']['#field_name'] == 'field_promoted_media'
      && in_array($variables['element']['#view_mode'], array('promoted_big', 'promoted_small'))) {

    // add a wrapper link to the image field
    foreach ($variables['items'] as $key => $item) {
      $wrapper = entity_metadata_wrapper('node', $variables['element']['#object']);
      if ($wrapper->field_promoted_content->value()) {
        $target_nid = $wrapper->field_promoted_content->value()->nid;
        $variables['items'][$key]['#prefix'] = '<a href="'. url("node/$target_nid") .'">';
        $variables['items'][$key]['#suffix'] = '</a>';
      }
    }
  }
}

/**
 * Implements hook_migrate_api().
 */
function oc_promote_migrate_api() {
  $api = array(
    'api' => 2,
    'migrations' => array(
      'OCPromote' => array('class_name' => 'OCPromote'),
    ),
  );
  return $api;
}

