sudo: false
notifications:
  email: false
  slack:
    secure: "LTnCgREJY7JDuUTBYljE5IG2CtTRawl5mZ6Lv/EVxWtQPE7P8kn5gnRJ1gQvETxCQt+F4/u5AKx51Mkh+ubAufWF6+OdLZvtWtnLVKmXuCQSrioRNUn7mzCweBZmBkbxCfND22ATsiUeeBqVPOX+m7e5G7kn0fGuZTHzuXBJ938="
    on_success: change
    on_failure: always

# No need for git history here
git:
 depth: 5

# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # aliased to a recent 5.4.x version
  - 5.5

mysql:
 database: drupal
 username: root
 encoding: utf8

# using travis ci cache mecanism
cache:
 directories:
  # caching composer stuff
  - $HOME/.composer/cache

install:

 - "mysql -e 'create database drupal;'"

 # Install latest Drush 6.
 - export PATH="$HOME/.composer/vendor/bin:$PATH"
 - composer config -g github-oauth.github.com 74e0b824ac52875a63fbaeab8396b710c50c7328
 - composer global require --no-interaction --prefer-dist drush/drush:6.*
 - drush dl -y drupalorg_drush-7.x-1.x-dev --destination=$HOME/.drush
 - drush cc drush

 # Build Behat dependencies
 - cd ./tests/behat
 - composer install --no-interaction --prefer-dist
 - cd ../../../

 # Setting Behat environment
 - DISTRO=`echo $TRAVIS_BUILD_DIR | sed -e "s/\/[^\/]*$//"`
 - export BEHAT_PARAMS="extensions[Drupal\\DrupalExtension\\Extension][drupal][drupal_root]=$DISTRO/drupal"

 # Build Codebase
 #- mkdir private_files
 - mkdir profiles
 - mv oc profiles/
 - mkdir drupal
 - mv profiles drupal/

 # Build the current branch
 - cd drupal
 - drush make --yes profiles/oc/drupal-org-core.make --prepare-install
 - drush make --yes profiles/oc/oc.make --no-core --contrib-destination=profiles/oc

 # Setup files
 #- chmod -R 777 sites/all

 # Setup display for Selenium
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 5

 # Get Selenium
 - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.1.jar
 - java -jar selenium-server-standalone-2.42.1.jar > /dev/null 2>&1 &
 - sleep 5

 # Disable sendmail
 - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
 # Do the site install
 - drush site-install oc --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=admin --site-mail=admin@example.com --site-name="Open Consortium" --yes
 - drush cc all
 # Check Features statuses, all should be clean
 - ./profiles/oc/tests/scripts/check_features_status.sh
 # Migrate processes
 #- drush mreg
 - drush mi --all
 # The institutions aren't geocoded when created, we have to save them again to trigger geocoding
 - drush mi OCPartners --update

 # Start server
 - drush runserver --server=builtin 8888 > /dev/null 2>&1 &
 - sleep 5

script:
 - pwd
 # Run Behat tests
 - cd profiles/oc/tests/behat
 - ./bin/behat --config behat.travis.yml
 - cd ../../../..
 - pwd

# Commit to deploy repo
after_success:
# Only deploy on tag
- if ([ -z "$TRAVIS_TAG" ]); then exit 0 ; fi
# Change to $HOME/build/marzeelabs
- cd ..
# Get current oc-drops-7
- git clone git@github.com:marzeelabs/oc-drops-7.git
# Replace OC Profile on oc-drops-7 with the one we just built
- rm -Rf oc-drops-7/profiles/oc
- cp -R drupal/profiles/oc oc-drops-7/profiles/oc
# Change to $HOME/build/marzeelabs/oc-drops-7/profiles/oc
- cd oc-drops-7/profiles/oc
# Get rid of all the git stuff so we don't commit as a submodule
- rm -Rf .git
- rm .gitignore
# Config git for our commit
- git config user.name "Marzee Labs"
- git config user.email "info@marzeelabs.org"
# Stage, commit and push back to Github
- git add --all :/
- git commit -m "OC Profile $TRAVIS_TAG"
- git push origin master
